version: '3'
services:
  mysql:
    image: mysql
    command: mysqld --character-set-server=latin1 --collation-server=latin1_swedish_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./src/test/resources/mysql_seed/:/docker-entrypoint-initdb.d
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
          - ./src/test/resources/psql_seed/:/docker-entrypoint-initdb.d
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
          - ./src/test/resources/mongo_seed/:/docker-entrypoint-initdb.d
