version: '3'
services:
  mysql:
    image: mysql
    command: mysqld --character-set-server=latin1 --collation-server=latin1_swedish_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./src/test/resources/seed/:/docker-entrypoint-initdb.d
